### ISSUE TITLE
Field highlighter is not visible for DatePicker

### ISSUE THREAD

**Issue by javier-godoy** [vaadin/collaboration-engine#22]
**Describe the bug**
When using Collaboration Engine, the field highlighter is not visible for DatePicker unless the DatePicker is focused _before_ opening the popup.

**To Reproduce**
1. Implement the example from https://vaadin.com/docs/v14/ce/tutorial.html:
2. Open the form in two tabs (view1, view2)
3. Focus the TextField in view1
4. Click on the calendar icon of DatePicker in view1 (without focusing the DatePicker)
5. The DatePicker popup opens and allows edition from view1
6. view2 doesn't display the field highlighter 😱

**Expected behavior**
view2 should display the field highlighter. 

Note that the field highlighter is visible in the following case:
1. Focus the DatePicker in view1
2. The DatePicker popup opens in view1
3. view2 correctly displays the field highlighter 😌

**Screenshots**
Observed behavior
![image](https://user-images.githubusercontent.com/11554739/104487974-85a74580-55ac-11eb-8aaa-327a9f655de7.png)

Expected behavior
![image](https://user-images.githubusercontent.com/11554739/104488026-9657bb80-55ac-11eb-8e71-cfb4dee06101.png)

**Versions**
    - Vaadin version: Vaadin 19.0.0.alpha2
    - Collaboration Engine version: 3.0.0.beta1
    - Java version: 11
    - OS version: Windows
    - Browser version: Chrome 87

**Comment by Peppe** [comment]
Thanks for the report!

@web-padawan, do you have some ideas on we could listen to the popup opener button to enable field highlighter? I guess we have something similar for opening combo box?

**Comment by web-padawan** [comment]
Issue moved to [vaadin/web-components #3553](https://github.com/vaadin/web-components/issues/3553) via [**ZenHub**](https://www.zenhub.com/)
