### ISSUE TITLE
CE does not work with BigDecimalField.

### ISSUE THREAD

**Issue by Peppe** [vaadin/collaboration-engine#3]
**Describe the bug**
This is a report from the customer during a call. Needs verification.

**To Reproduce**
1. Have a form with BigDecimalField
2. Use CollaborationBinder on the form.
3. Access the form in the browser
4. Notice errors in inspector

According to the customer, you get an error about some propery set or missing tag. The customer traced it back that Field-highlighters `field/outline.js` has a list of supported tags, and `vaadin-big-decimal-field` is not in the list, while for example `vaadin-number-field`is. Throwing an exception in either case is a little weird.

He said that the error went away as they white-listed collaboration engine packages within `application.properties`. It sounds a bit unrelated.

**Expected behavior**
BigDecimalField should work with Collaboration Engine.

**Versions**
    - Vaadin version: 14
    - Collaboration Engine version: 1.0.0.alpha14

**Comment by pekam** [comment]
I tried to reproduce. Field highlight works, but it's not tightly around the input like it should:
![image](https://user-images.githubusercontent.com/28533233/96968322-85515e00-1519-11eb-913d-06633c3aba3f.png)

**Comment by Peppe** [comment]
Here's a short clip on it for more context. Outline is in the wrong place, but everything still works. No errors in console.
![gif](https://user-images.githubusercontent.com/525503/96970354-3bb64280-151c-11eb-9b6c-1fbb524a52cf.gif)

**Comment by Peppe** [comment]
The outline of the field has been fixed so that the caption is not part of it, and it will be included in the next release.
