### ISSUE TITLE
In some cases Field highlighter is not visible.

### ISSUE THREAD

**Issue by Peppe** [vaadin/collaboration-engine#4]
**Describe the bug**
User noted that he got CE avatar group and binder value propagation to work, but he did not get the field highlighter to show. No clear instructions on how to reproduce, but he said he took a start.vaadin.com app and added CE there. However, our public demo is done exactly this way and it works. As the customer also reported #3, it could be that that issue broke the javascript and therefore did not render the field highlighter.

**Comment by pekam** [comment]
Maybe `@Push` was not enabled? That would cause all the updates to be non real-time, but it could seem like only the field highlight is not working in some scenarios: The updated field values and avatars will be propagated eventually when the client makes any request to the server, but if the focus on a field is lost in-between the requests, there's nothing to show.

**Comment by Peppe** [comment]
That's a good suggestion. I'll try to get the customer here to follow up on it.

**Comment by chrosim** [comment]
I don't remember if @Push was or wasn't enabled when we discovered this. I guess it was a mix of both or only #3

**Comment by Peppe** [comment]
That can be it. The code now warns if you are using CE features but Pus is not enabled. 

I'll close this issue down now. If you happen to notice this again, please reopen the issue.
