### ISSUE TITLE
[AvatarGroup] Avatar group should not have an auto width of 100%

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/collaboration-engine#62]
**Describe the bug**
Currently the avatar group has a width of 100 % set to it. This makes it necessary to add an extra step, when [this sample](https://vaadin.com/docs/latest/ce/components/collaboration-avatar-group/#displaying-users-own-avatar-separately) here shall be reproduced with a horizontal layout and positioning the elements at the right side (e.g. as it is known from google docs).

To fix this, the dev has to manually override the width to something like 
```
group.setWidth("auto");
```

Default:
![image](https://user-images.githubusercontent.com/36725474/156761524-98208e86-65fe-40b3-8a43-8753d3ea1f00.png)

Expected: 
![image](https://user-images.githubusercontent.com/36725474/156761407-1e4d81d4-b3b9-4975-96c5-b4a21b3d5465.png)

Sample code (in a vertical layout)
```
UserInfo userInfo = getUserInfo();

CollaborationAvatarGroup group = new CollaborationAvatarGroup(userInfo, getTopicId());
// Exclude own avatar from the group:
group.setOwnAvatarVisible(false);

Avatar ownAvatar = new Avatar();
ownAvatar.setName(userInfo.getName());
ownAvatar.setImage(userInfo.getImage());

HorizontalLayout avatars = new HorizontalLayout(group, ownAvatar);
avatars.setJustifyContentMode(JustifyContentMode.END);
add(avatars);

setHorizontalComponentAlignment(Alignment.END, group);

// this does not work
group.setSizeUndefined();

// this does work
group.setWidth("auto");
```

**Comment by web-padawan** [comment]
Issue moved to [vaadin/web-components #3554](https://github.com/vaadin/web-components/issues/3554) via [**ZenHub**](https://www.zenhub.com/)
