### ISSUE TITLE
User colors are not consistent across the cluster

### ISSUE THREAD

**Issue by heruan** [vaadin/collaboration-engine#66]
**Describe the bug**
Users connecting to app instances on different nodes will most probably see different colors assigned to the same users.

**To Reproduce**
1. Run the application in a cluster
2. Navigate to a view with a `CollaborationAvatarGroup`
3. Navigate to the same view targeting a different node

**Expected behavior**
User colors used in the avatars are consistent in the two nodes.

**Versions**
    - Vaadin version: 21.0
    - Collaboration Engine version: 5.0
    - Java version: 11

**Comment by MatthewVaadin** [comment]
This could be a good opportunity to introduce a topic for internal use that can store data like the user colors and distribute them across nodes in a cluster.

We already use this pattern with the `LicenseHandler` so we could either expand the use of that, or incorporate it into a new combined topic.

Note: We need to guard against accidental (or malicious) tampering of the topic. One way we could do this is to prefix all developer-generated topics with something (e.g. '$') and any internal topics either have different prefix or none.
