### ISSUE TITLE
Field highlighting is not visible for TextArea

### ISSUE THREAD

**Issue by chrosim** [vaadin/collaboration-engine#7]
The field highlighting should be visible for TextArea if another user starts editing.

**Versions**
    - Vaadin version: 14.4.0
    - Collaboration Engine version: 1.0.0.alpha14

The user tag is already displayed!

**Comment by Peppe** [comment]
Indeed. Tag is there, but highlight around the field is missing. Thank you for the report!
![Screenshot 2020-10-23 at 11 22 50 (2)](https://user-images.githubusercontent.com/525503/96974872-74f1b100-1522-11eb-9631-f0aff932c0ef.png)

**Comment by Peppe** [comment]
`TextArea` applies CSS `overflow` rules on top of `TextField`, which hides the outline. It needs the overflow-rule to scroll properly when there are prefix or suffix components attached to the field. We found an alternative way to attach the outline to the field, and have a patch ready. It will go through standard review processes and hopefully end in the next release.

**Comment by Peppe** [comment]
Hey. We released version 1.0.0 yesterday and this got a fix in that version. Please update and verify that it works.
